### ISSUE TITLE
RE: Organisationen abrufen ausarbeiten

### ISSUE THREAD

**Issue by johannes-weigel** [projectyouthclubstage/documentation#10]
Konzept der Organisation und dem Abrufen von Organisationen ausarbeiten und dokumentieren

**Comment by johannes-weigel** [comment]
Bitte [Anforderungen/2-organisations-groups.md](https://github.com/projectyouthclubstage/documentation/blob/master/Anforderungen/2-organisations-groups.md) bezüglich den Organisationen überprüfen - @Sadeeg88

**Comment by Sadeeg88** [comment]
@johannesWeigel  ist geprüft und ist ok aus meiner Sicht

**Comment by Sadeeg** [comment]
@johannesWeigel  ist geprüft und ist ok aus meiner Sicht
