### ISSUE TITLE
RE: Gruppen abrufen ausarbeiten

### ISSUE THREAD

**Issue by johannes-weigel** [projectyouthclubstage/documentation#11]
Konzept der Gruppen und dem Abrufen von Gruppen ausarbeiten und dokumentieren

**Comment by johannes-weigel** [comment]
Bitte [Anforderungen/2-organisations-groups.md](https://github.com/projectyouthclubstage/documentation/blob/master/Anforderungen/2-organisations-groups.md) bezüglich den Gruppen überprüfen - @Sadeeg88

**Comment by Sadeeg** [comment]
@johannesWeigel ist überprüft und für gut befunden :)
