### ISSUE TITLE
IS: Buildpipeline erweitern

### ISSUE THREAD

**Issue by Sadeeg** [projectyouthclubstage/documentation#13]
1. Steps nur im Master
2. Deployment nur per Eingabe
3. Version anstatt Buildnumber -> Datum+Version z.B. 190501-001-SNAPSHOT

**Comment by Sadeeg** [comment]
Deployment nur per Eingabe zurückgesteltt.
@johannesWeigel  Reicht eigentlich solange nur der Master auf Testumgebung deployed  oder soll ich ne Abfrage für Deployment einbauen?

**Comment by johannes-weigel** [comment]
Jo
