### ISSUE TITLE
IS: Buildpipeline bauen

### ISSUE THREAD

**Issue by johannes-weigel** [projectyouthclubstage/documentation#9]
Beispielhafte Pipeline bauen

**Comment by johannes-weigel** [comment]
Automatischer nginx-proxy muss eingerichtet werden

**Comment by johannes-weigel** [comment]
Green-Blue-Deployment fehlt

**Comment by Sadeeg** [comment]
Green - Blue Deployment funktioniert. Health Check muss noch überarbeitet weren
